### ISSUE TITLE
Create Variable creates invalid syntax in variable declarations

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#10]
## Describe the bug

When you execute the "Create Variable" action within the definition of an object literal the extension creates the variable declaration inside of the literal, generating invalid code.

## How to reproduce

```ts
const myObj = {
    hello: "world",
    magicNumber: myNumber
  };
```
Execute Create Variable for `myNumber`. This gets generated:

```ts
const myObj = {
    hello: "world",
    magicNumber: const myNumber = ;
    myNumber
  };
```

## Expected behavior

The variable should be declared outside of the literal block, like this:
```ts
const myNumber = ;
const myObj = {
    hello: "world",
    magicNumber: myNumber
  };
```

## Additional information

- Version of the extension impacted: _v1.2.0_

**Comment by automatensalat** [comment]
Actually the feature seems to be broken for the general case as well: 
```ts
const a = b;
```
-> create b
```ts
const a = const b = ;
    b;
```

**Comment by nicoespeon** [comment]
Nice! I think this is true whenever there's an assignment.

This is probably the offender: https://github.com/nicoespeon/hocus-pocus/blob/9d428b7caed78cd2a38af6ffb868e425ee8bc51d/src/create-variable.ts#L42

It's likely incorrect in such scenario.

**Comment by nicoespeon** [comment]
Fixed 😎 

![2020-05-01 Screenshot-w2z2KvL5](https://user-images.githubusercontent.com/1094774/80846886-c2c4d680-8bdb-11ea-8c7a-b8c457ec4ac6.gif)

Will ship a release tonight.
