### ISSUE TITLE
Create function should work with function references

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#11]
## Describe what's missing

For code like this: 
```ts
[1, 2, 3].forEach(print);
```
the extension only provides the `Create Variable` action for `print`. Instead, it would be nice to be able to create a function out of this too. 

## How would it work

I guess for the general case we'd need the infered types (#3). 
Perhaps we could introduce a special case for `forEach` functions until then.
For functions called `forEach` we'd generate a function signature that takes 1 parameter and returns `void`. 

This could work with `map` and `filter` as well.

## Expected behavior

The extension provide the `Create Function` action to create a matching function if executed on a function reference used as a function parameter.
## Additional information

- Version of the extension used: _v1.2.0_

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
