### ISSUE TITLE
Convert a `let` to `const` for a variable declaration where the context allows it

### ISSUE THREAD

**Issue by nickebbitt** [nicoespeon/hocus-pocus#14]
## Is this request related to a problem? Please describe.

Favouring immutability, it would be good to have a quick fix to convert a variable declaration from `let` to `const` if the scope and usage of the variable allows it.

## Describe the solution you'd like

Given the following code:
```
function getValue(): string {
   let someVariable = 'value';
   return someVariable;
}
```
A quick-fix on `someVariable` would allow conversion to this:
```
function getValue(): string {
   const someVariable = 'value';
   return someVariable;
}
```
Whereas it wouldn't be available for:
```
function getValue(): string {
   let someVariable = 'value';
   someVariable = 'anotherValue';
   return someVariable;
}
```

**Comment by nicoespeon** [comment]
That's a really good idea, I like it. However I think this would better suits the other extension: [Abracadabra](https://github.com/nicoespeon/abracadabra). I prefer to gather all refactorings into this extension, and that would clearly be a refactoring operation.

Hocus Pocus is more for creating convenient stuff (which is not refactoring).

Would you mind create the issue there instead? Thanks!
