### ISSUE TITLE
Use underlying type instead of narrowed literals for type inferrance

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#16]
## Describe what's missing

As of version 1.4 the extension adds the inferred type to function parameters when using the `Create Function` action in typescript files. When the argument is a literal though like `3` (number) or `"Hi"` (string) it will generate the parameter declaration using this narrowed type instead of the general type (`number` or `string`).
I suggest to substitute the narrowed type with the general type in the cases of primitive literals (in particular `string` and `enum`s). 

## How would it work

When analysing the argument types, the extension could special-case arguments of type `NumericLiteral` and `StringLiteral` and use `number` or `string` instead of the types received from the type checker. 

## Expected behavior

Instead of `doSomething("hello")` -> `function doSomething(param1: "hello")` we'd get `function doSomething(param1: string)`.

## Additional information

- Version of the extension used: _v1.4_

## Rationale
I'm thinking of use cases like this: 
```ts
logError("Oops, something went wrong");
```
or
```ts
throw new TotallyNonExistingError("I'm sorry Dave");
```
(last use case would be Create Class, but it's not using the types yet). Surely here the general `string` type would be more appropriate than the narrowed one.

**Comment by nicoespeon** [comment]
👍 I also thinks generic types are what you expect 99% of the time. Narrowed types are correct (TS inferred them) but they're not what we mean in general when we take this approach (using function before it's created, to craft the signature).

**Comment by nicoespeon** [comment]
I did some magic to resolve the generic type instead of these. That seems to work. Let me know if you find issues 👍
