### ISSUE TITLE
Create Function with Type generates "typeof" when used with Enums

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#19]
## Describe the bug

When executing `hocusPocus.createFunctionWithTypes` on code like this: 
```ts
enum Bla {
	A = 1,
	B = 2,
}

function bla() {
	doSomething(Bla.A);
}
```
It generates `typeof <Enum>` instead of `<Enum>` as the parameter type in the created function: 
```ts
function doSomething(param1: typeof Bla) {
  // Implement
}
```
TS will then complain about the argument not being assignable to the type of the parameter at the call site.

## How to reproduce

Define an `enum` and pass a enum value to an unknown function, execute the extension.

## Expected behavior

The extension should instead declare the parameter as the enum type, like this 
```ts
function doSomething(param1: Bla) {
  // Implement
} 
``` 

## Additional information

- Version of the extension impacted: _v1.4.0_

**Comment by nicoespeon** [comment]
Thanks for reporting, that's helpful to catch different patterns and edge-case (we still need to battle test this new feature!).

This is now fixed.
