### ISSUE TITLE
Creating a variable in `if` expression results in a mess

### ISSUE THREAD

**Issue by grandsong** [nicoespeon/hocus-pocus#20]
## Describe the bug

When I created a variable for a variable name in an `if` condition expression, new code was added **in** that condition instead of **before** it.

## How to reproduce

```ts
function test(n){
  if (n > max){
    // ...
  }
}
```

Create variable "max".

Then you will get:

```ts
function test(n){
  if (const max = ;
  n > max){
    // ...
  }
}
```

## Expected behavior

```ts
function test(n){
  const max = ;
  if (n > max){
    // ...
  }
}
```

**Comment by nicoespeon** [comment]
Thanks for reporting! Hopefully, by reporting different scenario the extension will handle all kind of situations. It's easy to handle these patterns.

I added a test and fixed this one. I also handled while and for statements.

I might still be missing some patterns. Don't hesitate to open new issues if you find them 👍
