### ISSUE TITLE
Add types to the 'create class' quick fix

### ISSUE THREAD

**Issue by nickebbitt** [nicoespeon/hocus-pocus#21]
## Is this request related to a problem? Please describe.

The *create class* quick-fix does not currently infer types. Introduction of the type checker in #3 should allow us to enhance (or provide an alternative quick-fix) that provides typing.

## Describe the solution you'd like

Given the code:
```
new MyClass('some string', 1234)
```
the quick-fix would generate a class with types for the constructor args:
```
class MyClass {
  constructor(param1: string, param2: number) {
    // Implement
  }
}
```

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
