### ISSUE TITLE
Switch: create all cases - doen't work when enum is exported

### ISSUE THREAD

**Issue by maciejewiczow** [nicoespeon/hocus-pocus#28]
## Describe the bug

Option `Create all cases` for switch statements does not seem to work when switch variable is typed with enum that has keyword `export` before `enum`. It creates an empty switch.

## How to reproduce

1. Create an enum that is a named export (`export enum Test { ... }`)
1. Try to use quick fix: create all cases on a switch with variable typed with that enum

## Expected behavior

Successfully creates a case for each member of the enum in question

## Screenshots

![2020-11-29_00h03_30](https://user-images.githubusercontent.com/37718435/100527868-fe0d9f00-31d6-11eb-9cf8-e871c48318b2.gif)

## Additional information

- Version of the extension impacted: _v1.7.0_

I have a lot of other extensions installed, but now I don't have the time to disable them all and try to reproduce this again.

**Comment by Triazic** [comment]
seconding this issue. same problem for me

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
