### ISSUE TITLE
Switch: create all cases - comments from enum are inserted mid-through generated cases

### ISSUE THREAD

**Issue by maciejewiczow** [nicoespeon/hocus-pocus#29]
## Describe the bug

When using quick fix: create all cases for switch with enum variable, which enum had comments between members, comments from enum are inserted mid-through generated switch cases (screenshot).

## How to reproduce

1. Create an enum that has comments inside
1. Use `create all cases` for switch

## Expected behavior

Comments are omitted, and if not, then they at least shouldn't be inserted mid-case (screenshot)

## Screenshots

![2020-11-29_00h05_39](https://user-images.githubusercontent.com/37718435/100527979-f1d61180-31d7-11eb-9ee6-dbf1a0606348.gif)

## Additional information

- Version of the extension impacted: _v1.7.0_

I have a lot of other extensions installed, but now I don't have the time to disable them all and try to reproduce this again.

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
