### ISSUE TITLE
Switch: create all cases - doesnt work for dynamic union type

### ISSUE THREAD

**Issue by SalehTechLab** [nicoespeon/hocus-pocus#37]
## Describe the bug

I have dynamic union type as `type Animal = "cat" | "dog" | "rabbit" | "snake"` coming from string literal type of array values and I don't see the option `Create all cases`

## How to reproduce

try to use the following code :
````
export type Lit = string | number | boolean | undefined | null | void | {};
export const tuple = <T extends Lit[]>(...args: T) => args;

const animals = tuple('cat', 'dog', 'rabbit', 'snake');
type Animal = (typeof animals)[number];  // union type

function getAnimalInfo(value: Animal): string {
  switch (value) {
  }
}
````

## Expected behavior

Successfully creates a case for each member of the union type like 

````
function getAnimalInfo(value: Animal): string {
  switch (value) {
    case 'cat':
      return 'Here is some info';
    case 'dog':
      return 'Here is some info';
    case 'rabbit':
      return 'Here is some info';
    case 'snake':
      return 'Here is some info';
    default:
      return '';
  }
}
````

## Screenshots

<img width="512" alt="Screenshot 2021-07-07 at 13 47 07" src="https://user-images.githubusercontent.com/17778023/124753910-d8ddcd80-df29-11eb-9137-4835901f236b.png">

## Additional information

- Version of the extension impacted: _v1.7.0_

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
