### ISSUE TITLE
Generate async function when invoked with await

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#4]
## Describe what's missing

When the "generate function" feature of the extension is invoked on code that has the `await` modifier, I expect the generated function to come with a `async` modifier.

## How would it work

The extension would check if the not-yet-existing function has the `await` keyword or not. If yes, then `async ` is prepended to the generated function.

## Expected behavior

E.g.
```ts
const result = await doSomething();
```
Would generate
```ts
async doSomething() {
}
```

- Version of the extension used: _v1.1.0_

**Comment by nicoespeon** [comment]
Released in version 1.2.0. Thank you 👍
