### ISSUE TITLE
Add extension to Open VSX Registry

### ISSUE THREAD

**Issue by remusa** [nicoespeon/hocus-pocus#44]
## Describe what's missing

The extension can't be found in Open VSX Registry

## How would it work

The extension would be available in Open VSX Registry (same as the Abracadabra one by the same author).

**Comment by tennox** [comment]
[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

For that reason, I can't use your extension anymore, could you publish on OpenVSX too?
(It's typically just a matter of running `npx ovsx publish` you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
