### ISSUE TITLE
Code Action dropped in VSCode

### ISSUE THREAD

**Issue by tsteckenborn** [nicoespeon/hocus-pocus#50]
## Describe the bug

VSCode Extension Host displays the warning: "2022-12-21 15:02:42.636 [warning] nicoespeon.hocus-pocus - Code actions of kind 'quickfix 'requested but returned code action does not have a 'kind'. Code action will be dropped. Please set 'CodeAction.kind'."

## Expected behavior

No warnings were thrown.

## Additional information

- Version of the extension impacted: _ v1.7.0 _

_🔮‍ Add any other context about the problem here._
Not sure about the actual impact, but seeing that warning repeated seven times in the extension host output.

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
